/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;
// aki se importa todas las librerias que se van a utilizar:

import dao.ProductosDAO;
import dto.ProductosDTO;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author Oropeza
 */
public class Productoform extends javax.swing.JInternalFrame {
 private ProductosDAO dAO = new ProductosDAO();
    private List<ProductosDTO> lista = new ArrayList<>();
    private DefaultTableModel dtm;
    String product, fecharegis, fechaven, categoria, serie, marca; int id, idprec, cant, idlogueo; double preciocomp;
    ProductosDTO p;
    /**
     * Creates new form Producto
     */
    
    //IMPORTANDO ARAYLIST:::::
//    ProductosDTO dto;
////    ProductosDAO dAO= new ProductosDAO();
////    ArrayList<ProductosDTO> lista = new ArrayList<>();
//    DefaultTableModel modelo, modelo1;
    
    //fin:::::::::::
    public Productoform() {
        initComponents();
            }
    
    //metodo para cargar la tabla al array:::::::::::::::

    public  void cargarTableArray(){
        
         dtm = (DefaultTableModel) tbproducto.getModel();
        lista = dAO.getLista();       
        Object []datos = new Object[11];
        for (int i=0 ; i<lista.size(); i++){
            
            datos[0]=i+1;
            datos[1]=lista.get(i).getProducto();
            datos[2]=lista.get(i).getSerie();
            datos[3]=lista.get(i).getMarca();
            datos[4]=lista.get(i).getCantegoria();
            datos[5]=lista.get(i).getFecharegis();
            datos[6]=lista.get(i).getFechaven();
            datos[7]=lista.get(i).getCantidad();
            datos[8]=lista.get(i).getPreciocomp();
            datos[9]=lista.get(i).getIdlogueo();
            datos[10]=lista.get(i).getIdprecio();
            dtm.addRow(datos);
            
        }
        tbproducto.setModel(dtm);
    }
     //cargar la tabla de la base de datos:::::::::::
    public  void cargarTabla(){
        
         dtm = (DefaultTableModel) tbproducto.getModel();
        lista = dAO.listarProducto();       
        Object []datos = new Object[11];
        for (int i=0 ; i<lista.size(); i++){
            
            datos[0]=lista.get(i).getIdproducto();
            datos[1]=lista.get(i).getProducto();
            datos[2]=lista.get(i).getSerie();
            datos[3]=lista.get(i).getMarca();
            datos[4]=lista.get(i).getCantegoria();
            datos[5]=lista.get(i).getFecharegis();
            datos[6]=lista.get(i).getFechaven();
            datos[7]=lista.get(i).getCantidad();
            datos[8]=lista.get(i).getPreciocomp();
            datos[9]=lista.get(i).getIdlogueo();
            datos[10]=lista.get(i).getIdprecio();
            dtm.addRow(datos);
            
        }
        tbproducto.setModel(dtm);
    }
         
    public void limpiarTabla(){
      int a =dtm.getRowCount()-1;  
        for(int i=a;i>=0;i--){  
            dtm.removeRow(i);
        }
 }
// fin:::::
   //registrando en el array list::::::::::::::
    
    public void registrarproductoArray(){
       String producto = txtproducto.getText();
       double preciocomp = Double.parseDouble(txtprecio_compra.getText());
       int  idprec = Integer.parseInt(txtprecio.getText());
       int cant = Integer.parseInt(txtcantidad.getText());
           SimpleDateFormat Formato = new SimpleDateFormat("yyyy-MM-dd");
        String fecharegis = Formato.format(dcfecha_reg.getDate());
        
  SimpleDateFormat Format = new SimpleDateFormat("yyyy-MM-dd");
        String fechaven = Format.format(dcfecha_vent.getDate());
       
        String categoria = txtcategoria.getText();
       String serie = txtserie.getText();
       String marca = txtmarca.getText();
       int idlogueo = Integer.parseInt(txtloge.getText());
        p = new ProductosDTO(producto, serie ,marca, categoria,fecharegis,fechaven,cant,preciocomp,  idlogueo ,  idprec);
        dAO.añadirproducto(p);
        
        cargarTableArray();
        limpiarTabla();
        cargarTableArray();
        
} 
    //finnnn
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtmarca = new javax.swing.JTextField();
        txtserie = new javax.swing.JTextField();
        txtproducto = new javax.swing.JTextField();
        txtidproducto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtcategoria = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtprecio_compra = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtcantidad = new javax.swing.JTextField();
        btnmodificarproducto = new javax.swing.JButton();
        btnañadirproducto = new javax.swing.JButton();
        btnquitarproducto = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        txtprecio = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtloge = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        btncargartabla = new javax.swing.JButton();
        dcfecha_reg = new com.toedter.calendar.JDateChooser();
        dcfecha_vent = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbproducto = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnaceptar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();

        setClosable(true);
        setTitle("REGISTRODE PRODUCTOS");

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del Producto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Aharoni", 1, 12))); // NOI18N

        txtidproducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtidproductoMouseEntered(evt);
            }
        });
        txtidproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidproductoActionPerformed(evt);
            }
        });
        txtidproducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtidproductoKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("idProducto:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Producto:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Serie:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Marca:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Fecha_Registro:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Categoria:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Precio_Compra:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Precio_Venta:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Cantidad:");

        btnmodificarproducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/modifcar.png xddddd.png"))); // NOI18N
        btnmodificarproducto.setText("MODIFICAR");
        btnmodificarproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificarproductoActionPerformed(evt);
            }
        });

        btnañadirproducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/anadi.png"))); // NOI18N
        btnañadirproducto.setText("AÑADIR");
        btnañadirproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnañadirproductoActionPerformed(evt);
            }
        });

        btnquitarproducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/quitar.png"))); // NOI18N
        btnquitarproducto.setText("QUITAR");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar", "Item 2", "Item 3", "Item 4" }));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Fecha_Venta:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Precio: ");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("idlogueo:");

        btncargartabla.setText("CARGAR TABLA");
        btncargartabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncargartablaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(btnañadirproducto)
                        .addGap(39, 39, 39)
                        .addComponent(btnmodificarproducto)
                        .addGap(46, 46, 46)
                        .addComponent(btnquitarproducto))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtidproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtserie, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dcfecha_reg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dcfecha_vent, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtproducto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtcategoria)
                                .addComponent(txtloge, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtmarca, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox1, 0, 174, Short.MAX_VALUE)
                            .addComponent(txtprecio_compra)
                            .addComponent(txtcantidad)
                            .addComponent(txtprecio)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(btncargartabla, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtproducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtidproducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtserie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(txtmarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(txtprecio_compra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dcfecha_reg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(txtcategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel9)
                                .addComponent(txtcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dcfecha_vent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(txtloge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11)
                                    .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(1, 1, 1)))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnañadirproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnmodificarproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnquitarproducto)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btncargartabla, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17))
        );

        tbproducto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        tbproducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IdPrroducto", " Producto", "Nº Serie", "Marca", "Categoria", "Fecha_Registro", "Fecha_Venta", "Cantidad", "Precio_Compra", "IdLogueo", "IdPrecio"
            }
        ));
        tbproducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbproductoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbproducto);
        if (tbproducto.getColumnModel().getColumnCount() > 0) {
            tbproducto.getColumnModel().getColumn(0).setMaxWidth(200);
            tbproducto.getColumnModel().getColumn(1).setMaxWidth(150);
            tbproducto.getColumnModel().getColumn(2).setMaxWidth(150);
            tbproducto.getColumnModel().getColumn(3).setMaxWidth(50);
            tbproducto.getColumnModel().getColumn(9).setMaxWidth(80);
            tbproducto.getColumnModel().getColumn(10).setMaxWidth(80);
        }

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "AGREGAR PRODUCTO", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        btnaceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/aceptar.png"))); // NOI18N
        btnaceptar.setText("ACEPTAR");
        btnaceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaceptarActionPerformed(evt);
            }
        });

        btncancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cancel.png"))); // NOI18N
        btncancelar.setText("CANCELAR");
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(btncancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 259, Short.MAX_VALUE)
                .addComponent(btnaceptar)
                .addGap(24, 24, 24))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnaceptar)
                    .addComponent(btncancelar))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 43, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(128, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtidproductoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidproductoKeyPressed
//
//        if(evt.getKeyChar()){
//            
//        }
            
            
//        JOptionPane.showMessageDialog();

       
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidproductoKeyPressed
    
    private void btnañadirproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnañadirproductoActionPerformed
        
      
        registrarproductoArray();
        
        //añadir producto::::::::::::::
        
//       String product = txtproducto.getText();
//       double preciocomp = Double.parseDouble(txtprecio_compra.getText());
//       int  idprec = Integer.parseInt(txtprecio.getText());
//        int cant = Integer.parseInt(txtcantidad.getText());
//       String fecharegis = txtfe.getText();
//       String fechaven = txtfech_vent.getText();
//       String categoria = txtcategoria.getText();
//        String serie = txtserie.getText();
//       String marca = txtmarca.getText();
//       int idlogueo = Integer.parseInt(txtloge.getText());
//                        
//       p = new ProductosDTO(product, preciocomp, idprec, cant, idlogueo ,fecharegis,fechaven, categoria, serie ,marca);
//        
//        if(dAO.agregarProducto(p)){
//            JOptionPane.showMessageDialog(null, "producto registrado!!");
//            limpiarTabla();
//            cargarTabla();
//        }else{
//            JOptionPane.showMessageDialog(null, "producto no registrado!!");
//        }
//        

// TODO add your handling code here:
    }//GEN-LAST:event_btnañadirproductoActionPerformed

//limpiar campos de la tabla PRODUCTOS:::::
  public  void limpiar(){
        txtidproducto.setText(null);
        txtcantidad.setText(null);
        txtcategoria.setText(null);
        txtmarca.setText(null);
        txtproducto.setText(null);
//        txtfe.setText(null);
               
    }
    
    
    private void txtidproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidproductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidproductoActionPerformed

    private void btnaceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaceptarActionPerformed

        //agregar a la base de datos
        
// TODO add your handling code here:
    }//GEN-LAST:event_btnaceptarActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed

        //cancelar venta 
        
        
// TODO add your handling code here:
    }//GEN-LAST:event_btncancelarActionPerformed

    private void txtidproductoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtidproductoMouseEntered
       
// TODO add your handling code here:
    }//GEN-LAST:event_txtidproductoMouseEntered

    private void tbproductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbproductoMouseClicked
if(tbproducto.getSelectedRow()>=0){
   
            int fila = tbproducto.getSelectedRow(); 
            txtproducto.setText(tbproducto.getValueAt(fila, 1).toString());
            txtidproducto.setText(tbproducto.getValueAt(fila, 0).toString());
           // txtfe.setText(tbproducto.getValueAt(fila, 3).toString());
            id = Integer.parseInt(tbproducto.getValueAt(fila, 0).toString());
        }
        

// TODO add your handling code here:
    }//GEN-LAST:event_tbproductoMouseClicked

    private void btnmodificarproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarproductoActionPerformed
        product = txtproducto.getText();
        preciocomp = Double.parseDouble(txtprecio_compra.getText());
        idprec = Integer.parseInt(txtprecio.getText());
        cant = Integer.parseInt(txtcantidad.getText());
            SimpleDateFormat Formato = new SimpleDateFormat("yyyy-MM-dd");
//        String fecharegis = Formato.format(dcfecha_reg.getDate());
//       
//        
//        fecharegis = txtfe.getText();
//        fechaven = txtfech_vent.getText();
        categoria = txtcategoria.getText();
        serie = txtserie.getText();
        marca = txtmarca.getText();
        idlogueo = Integer.parseInt(txtloge.getText());
  
          p.setIdproducto(id);
                p.setProducto(product);
                p.setPreciocomp(preciocomp);
                p.setIdprecio(idprec);
                p.setCantidad(cant);
                p.setFecharegis(fecharegis);
                p.setFechaven(fechaven);
                p.setCantegoria(categoria);
                p.setSerie(serie);
                p.setMarca(marca);
                p.setIdlogueo(idlogueo);
        
         JOptionPane.showMessageDialog(null, id);
        //u = new Usuario(nombre, apellidos, user, pass, estado);
        if(dAO.editarProducto(p)){
            JOptionPane.showMessageDialog(null, "producto Modificado!!");
            limpiarTabla();
            cargarTabla();
        }else{
            JOptionPane.showMessageDialog(null, "producto no Modificado!!");
        }        
// TODO add your handling code here:
    }//GEN-LAST:event_btnmodificarproductoActionPerformed

    private void btncargartablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncargartablaActionPerformed
//cargando tabla::::::::::
        cargarTabla();
 
    }//GEN-LAST:event_btncargartablaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaceptar;
    private javax.swing.JButton btnañadirproducto;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btncargartabla;
    private javax.swing.JButton btnmodificarproducto;
    private javax.swing.JButton btnquitarproducto;
    private com.toedter.calendar.JDateChooser dcfecha_reg;
    private com.toedter.calendar.JDateChooser dcfecha_vent;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbproducto;
    private javax.swing.JTextField txtcantidad;
    private javax.swing.JTextField txtcategoria;
    private javax.swing.JTextField txtidproducto;
    private javax.swing.JTextField txtloge;
    private javax.swing.JTextField txtmarca;
    private javax.swing.JTextField txtprecio;
    private javax.swing.JTextField txtprecio_compra;
    private javax.swing.JTextField txtproducto;
    private javax.swing.JTextField txtserie;
    // End of variables declaration//GEN-END:variables
}
